FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /processor ./cmd/processor

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=build /processor /processor
CMD ["/processor"]
